version: '2'

services:

  pycharm:
    build: .
    image: ${DOCKER_HUB_USER}pycharm-community:2016.2.3
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ${HOME}:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
